- platform: manual
  code: !secret alarm_code
  code_arm_required: false
  arming_time: 60  # The time in seconds of the ‘arming’ state
  delay_time: 60  # The time in seconds of the ‘pending’ state before triggering the alarm
  armed_night:
    arming_time: 0