- platform: generic_thermostat
  name: Bathroom
  unique_id: 918af0b6-8e24-4f9f-b640-c9f12ac079fd
  heater: switch.zwater_bad
  target_sensor: sensor.bathroom_temperature_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Hall
  unique_id: 01a1ccd6-b213-4c6c-95df-590bdc7ba3fe
  heater: switch.zwater_gang
  target_sensor: sensor.gang_temperatur_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Kitchen
  unique_id: 22593d6a-58a1-4330-b5ea-84a55c060224
  heater: switch.zwater_kjokken
  target_sensor: sensor.kjokken_temperatur_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Master Bedroom
  unique_id: 6eca3940-7e48-48cc-bb06-cbe199da762e
  heater: switch.zwater_master
  target_sensor: sensor.master_temperature_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Pia
  unique_id: 0d914d27-73d6-4e14-8536-1bff9de054eb
  heater: switch.zwater_pia
  target_sensor: sensor.pia_temperature_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Living Room
  unique_id: 842cac85-313f-46bd-bfbe-bad4da390040
  heater: switch.zwater_stue
  target_sensor: sensor.stue_temperatur_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Sverre
  unique_id: 587fc171-e828-436b-8bd6-a6d4e9a22b2d
  heater: switch.zwater_sverre
  target_sensor: sensor.sverre_temperature_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: TV
  unique_id: bc057343-3c2b-4c90-9091-8c0aff27d607
  heater: switch.zwater_tv_stue
  target_sensor: sensor.tv_stue_temperatur_calc
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
- platform: generic_thermostat
  name: Cinema
  unique_id: ce7e4ab6-dcfa-4733-98eb-b5ccbbd07915
  heater: switch.zwater_cinema
  target_sensor: sensor.cinema_temperature
  min_temp: 15
  max_temp: 30
  min_cycle_duration:
    minutes: 20
  cold_tolerance: 0
  hot_tolerance: 0
  away_temp: 15
