homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
climate: !include climate.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
influxdb: !include influx.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_numbers.yaml
mqtt: !include mqtt.yaml
plant: !include plants.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
    
####################
### INTEGRATIONS ###
####################

media_player:
  - platform: lg_netcast
    host: !secret lg_ip
    access_token: !secret lg_access_token

stream:

calendar:
  - platform: caldav
    url: https://caldav.icloud.com
    username: !secret cal_user
    password: !secret cal_pass
    calendars:
     - Family

powercalc: