homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warning
  logs:
    custom_components.energyscore: debug

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
climate: !include climate.yaml
homekit: !include homekit.yaml
influxdb: !include influx.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_numbers.yaml
mqtt: !include mqtt.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
    
####################
### INTEGRATIONS ###
####################

media_player:
  - platform: lg_netcast
    host: !secret lg_ip
    access_token: !secret lg_access_token

stream:

calendar:
  - platform: caldav
    url: https://caldav.icloud.com
    username: !secret cal_user
    password: !secret cal_pass
    calendars:
     - Family

powercalc:

###############
### FOR DEV ###
###############

mqtt_statestream:
  base_topic: ha-dev
  publish_attributes: true
  publish_timestamps: true
  include:
    entities:
      - sensor.electricity_price
      - sensor.total_energy_consumption
      - sensor.washer_energy
      - sensor.dishwasher_energy
      - sensor.nordpool_price