homeassistant:
  customize: !include customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
#camera: !include cameras.yaml
climate: !include climate.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
influxdb: !include influx.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_numbers.yaml
ios: !include ios.yaml
light: !include lights.yaml
modbus: !include modbus.yaml
plant: !include plants.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
#switch: !include switches.yaml
utility_meter: !include utility_meters.yaml
    
####################
### INTEGRATIONS ###
####################

media_player:
  - platform: lg_netcast
    host: !secret lg_ip
    access_token: !secret lg_access_token

stream:

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  include:
    entities:
      - sensor.apartment_bathroom_temperature
      - sensor.apartment_kitchen_temperature
