###############
# ENERGYSCORE #
###############

sensor:
  - platform: energyscore
    name: CTC Immersion Heater Energy Score
    unique_id: 5A4E0A34-0428-41D0-9534-26B759673868
    price_entity: sensor.nordpool_price
    energy_entity: sensor.ctc_immersion_heater_energy

####################
# TEMPLATE SENSORS #
####################

  - platform: template
    sensors:
      total_energy_score_quality:
        friendly_name: Total Energy Score Quality
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.total_energy_score', 'quality') * 100 }}"
      ev_energy_score_quality:
        friendly_name: EV Energy Score Quality
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ev_energy_score', 'quality') * 100 }}"
      ctc_immersion_heater_energy_score_quality:
        friendly_name: CTC Immerstion Heater Energy Score Quality
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.ctc_immersion_heater_energy_score', 'quality') * 100 }}"
      washer_energy_score_quality:
        friendly_name: Washer Energy Score Quality
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.washer_energy_score', 'quality') * 100 }}"
      washer_potential_percentage:
        friendly_name: Potential Savings Percentage
        unit_of_measurement: '%'
        value_template: "{{ (states('sensor.washer_potential_savings') | float / states('sensor.washer_cost') | float) | round(3) * 100 }}"

utility_meter:
  total_energy_score_utility:
    source: sensor.total_energy_score
    cycle: daily
    unique_id: 8F66A020-1799-4F22-BBDD-B8FC15AE7916
