plant:
  27:
    sensors:
      moisture: sensor.plant27_moisture
      temperature: sensor.plant27_temperature
      conductivity: sensor.plant27_conductivity
      brightness: sensor.plant27_light
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 2500
    max_brightness: 35000
    min_temperature: 8
    max_temperature: 32
  #48:
  #  sensors:
  #    moisture: sensor.plant48_moisture
  #    temperature: sensor.plant48_temperature
  #    conductivity: sensor.plant48_conductivity
  #    brightness: sensor.plant48_light
  #  min_moisture: 15
  #  max_moisture: 60
  #  min_conductivity: 350
  #  max_conductivity: 2000
  #  min_brightness: 2500
  #  max_brightness: 50000
  #  min_temperature: 5
  #  max_temperature: 35
  110:
    sensors:
      moisture: sensor.plant110_moisture
      temperature: sensor.plant110_temperature
      conductivity: sensor.plant110_conductivity
      brightness: sensor.plant110_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1500
    max_brightness: 20000
    min_temperature: 8
    max_temperature: 32
  129:
    sensors:
      moisture: sensor.plant129_moisture
      temperature: sensor.plant129_temperature
      conductivity: sensor.plant129_conductivity
      brightness: sensor.plant129_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 800 
    max_brightness: 15000
    min_temperature: 12
    max_temperature: 32
  165:
    sensors:
      moisture: sensor.plant165_moisture
      temperature: sensor.plant165_temperature
      conductivity: sensor.plant165_conductivity
      brightness: sensor.plant165_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 2000
    max_brightness: 35000
    min_temperature: 10
    max_temperature: 35
  166:
    sensors:
      moisture: sensor.plant166_moisture
      temperature: sensor.plant166_temperature
      conductivity: sensor.plant166_conductivity
      brightness: sensor.plant166_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1500
    max_brightness: 45000
    min_temperature: 12
    max_temperature: 32
  # 167:
  #   sensors:
  #     moisture: sensor.plant167_moisture
  #     temperature: sensor.plant167_temperature
  #     conductivity: sensor.plant167_conductivity
  #     brightness: sensor.plant167_light
  #   min_moisture: 15
  #   max_moisture: 65
  #   min_conductivity: 350
  #   max_conductivity: 1000
  #   min_brightness: 800
  #   max_brightness: 20000
  #   min_temperature: 12
  #   max_temperature: 32
  174:
    sensors:
      moisture: sensor.plant174_moisture
      temperature: sensor.plant174_temperature
      conductivity: sensor.plant174_conductivity
      brightness: sensor.plant174_light
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1000
    max_brightness: 22500
    min_temperature: 15
    max_temperature: 32
  175:
    sensors:
      moisture: sensor.plant175_moisture
      temperature: sensor.plant175_temperature
      conductivity: sensor.plant175_conductivity
      brightness: sensor.plant175_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1000
    max_brightness: 15000
    min_temperature: 8
    max_temperature: 35
  #185:
  #  sensors:
  #    moisture: sensor.plant185_moisture
  #    temperature: sensor.plant185_temperature
  #    conductivity: sensor.plant185_conductivity
  #    brightness: sensor.plant185_light
  #  min_moisture: 15
  #  max_moisture: 60
  #  min_conductivity: 350
  #  max_conductivity: 2000
  #  min_brightness: 3600
  #  max_brightness: 50000
  #  min_temperature: 10
  #  max_temperature: 35
  189:
    sensors:
      moisture: sensor.plant189_moisture
      temperature: sensor.plant189_temperature
      conductivity: sensor.plant189_conductivity
      brightness: sensor.plant189_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1400
    max_brightness: 45000
    min_temperature: 10
    max_temperature: 35
  190:
    sensors:
      moisture: sensor.plant190_moisture
      temperature: sensor.plant190_temperature
      conductivity: sensor.plant190_conductivity
      brightness: sensor.plant190_light
    min_moisture: 7
    max_moisture: 50
    min_conductivity: 300
    max_conductivity: 1000
    min_brightness: 3700
    max_brightness: 20000
    min_temperature: 10
    max_temperature: 32
  191:
    sensors:
      moisture: sensor.plant191_moisture
      temperature: sensor.plant191_temperature
      conductivity: sensor.plant191_conductivity
      brightness: sensor.plant191_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 800 
    max_brightness: 15000
    min_temperature: 12
    max_temperature: 32
  211:
    sensors:
      moisture: sensor.plant211_moisture
      temperature: sensor.plant211_temperature
      conductivity: sensor.plant211_conductivity
      brightness: sensor.plant211_light
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 3600
    max_brightness: 50000
    min_temperature: 10
    max_temperature: 35

################
# CUSTOM NAMES #
################

homeassistant:
  customize:
    plant.26:
      friendly_name: Draketre (Dracaena Marginata)
    plant.27:
      friendly_name: Fiken (Ficus Microcarpa Nitida)
    plant.30:
      friendly_name: Fiken (Ficus Benjamina)
    plant.31:
      friendly_name: Fiken (Ficus Benjamina)
    plant.48:
      friendly_name: Vindmøllepalme (Trachycarpus Fortunei)
    plant.72:
      friendly_name: Peter P. (Capsicum Annuum)
    plant.75:
      friendly_name: Cherry Bomb (Capsicum Annuum)
    plant.78:
      friendly_name: Aji Charapita (Capsicum Chinense)
    plant.83:
      friendly_name: Bulgarian Carrot (Capsicum Annuum)
    plant.105:
      friendly_name: Arekapalme (Dypsis Lutescens)
    plant.107:
      friendly_name: Paraplypalme (Schefflera Arboricola)
    plant.110:
      friendly_name: Yuccapalme (Yucca Elephantipes)
    plant.129:
      friendly_name: Monstera (Monstera Deliciosa)
    plant.165:
      friendly_name: Arekapalme (Dypsis Lutescens)
    plant.166:
      friendly_name: Fiolinfiken (Ficus lyrata)
    plant.167:
      friendly_name: Calathea (Calathea orbifolia)
    plant.174:
      friendly_name: Fredslilje (Spathiphyllum Sebastiano)
    plant.175:
      friendly_name: Philodendron (Rojo Congo)
    #plant.185:
    #  friendly_name: Praktspragle (Coleus)
    plant.189:
      friendly_name: Hengeeføy (Hedera Helix)
    plant.190:
      friendly_name: Dischidia Ovata
    plant.191:
      friendly_name: Monstera (Monstera Deliciosa)
    plant.211:
      friendly_name: Praktspragle (Coleus royale)